services:
  web: 
    build:
      context: app
      target: builder
    ports: 
      - '8000:8000'
      - '7070:8080'
       - '6060:8080'
       Hi team, good morning
              Hi team, good morning
